encoding: "utf-8"
title: Igor Agapie
description: Highly-skilled software development professional bringing more than 9 years in software design, development and integration. Advanced knowledge of PHP7 and C#.

avatar: profile2.jpg
social:
  github: http://github.com/iagapie
  linkedin: https://linkedin.com/in/iagapie
  instagram: https://www.instagram.com/mounflow
  twitter: https://twitter.com/@i_agapie

sass:
  sass_dir: _sass
  style: compressed

compress-site: yes

compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
